# Generated by Django 6.0.3 on 2026-03-11 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('openings', models.IntegerField()),
                ('salary', models.ImageField(upload_to='')),
                ('job_type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiterprofile')),
            ],
        ),
    ]
